name: "gatk4_bedtointervallist"
description: Converts a BED file to a Picard-style IntervalList file.
keywords:
  - gatk4
  - bedtointervallist
  - bed
  - interval_list
tools:
  - "gatk4":
      description: "Genome Analysis Toolkit (GATK) is a structured software package for analysis of high-throughput sequencing data."
      homepage: "https://gatk.broadinstitute.org/hc/en-us"
      documentation: "https://gatk.broadinstitute.org/hc/en-us/articles/360036882451-BedToIntervalList-Picard-"
      tool_dev_url: "https://github.com/broadinstitute/gatk"
      doi: ""
      licence: ["BSD-3-Clause"]
      identifier: biotools:gatk

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - bed:
        type: file
        description: Input BED file
        pattern: "*.{bed}"
        ontologies:
          - edam: "http://edamontology.org/format_3003" # BED
  - - meta2:
        type: map
        description: |
          Groovy Map containing sequence dictionary information
          e.g. `[ id:'genome' ]`
    - dict:
        type: file
        description: Sequence dictionary (.dict) file
        pattern: "*.dict"
        ontologies: []

output:
  interval_list:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.interval_list":
          type: file
          description: Converted interval list file
          pattern: "*.interval_list"
  versions_gatk4:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "gatk4":
          type: string
          description: The name of the tool
      - "gatk --version | sed -n '/GATK.*v/s/.*v//p'":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "gatk4":
          type: string
          description: The name of the tool
      - "gatk --version | sed -n '/GATK.*v/s/.*v//p'":
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@LoaiEletr"
maintainers:
  - "@LoaiEletr"
