name: "multiqc"
description: |
  Aggregates results from bioinformatics analyses across many samples into a single report.
  MultiQC searches a given directory for analysis logs and compiles a HTML report.
keywords:
  - quality control
  - qc
  - report
  - visualization
  - summary
tools:
  - multiqc:
      description: "Aggregate results from bioinformatics analyses across many samples into a single report"
      homepage: "https://multiqc.info/"
      documentation: "https://multiqc.info/docs/"
      tool_dev_url: "https://github.com/ewels/MultiQC"
      licence: ["GPL-3.0-or-later"]
      identifier: "MultiQC"

input:
  - multiqc_files:
      type: file
      description: |
        Directory or files containing analysis outputs from various tools for MultiQC to parse
      pattern: "**/*"
      ontologies: []
  - multiqc_config:
      type: file
      description: |
        Optional config yml for MultiQC
      pattern: "*.{yml,yaml}"
      ontologies:
        - edam: http://edamontology.org/format_3750

output:
  report:
    - "*.html":
        type: file
        description: |
          HTML report summarizing all quality control metrics from various analysis tools
        pattern: "*.html"

  data:
    - "*_data":
        type: file
        description: |
          Directory containing parsed data from MultiQC for downstream analysis
        pattern: "*_data/**"

  plots:
    - "*_plots":
        type: file
        description: |
          Directory containing individual plots generated by MultiQC
        pattern: "*_plots/**"
        optional: true

  versions_multiqc:
    - - "${task.process}":
          type: string
          description: The name of the process
      - multiqc:
          type: string
          description: The name of the MultiQC tool
      - "multiqc --version | sed 's/.*version //'":
          type: eval
          description: The expression to obtain the version of MultiQC

topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - multiqc:
          type: string
          description: The name of the MultiQC tool
      - "multiqc --version | sed 's/.*version //'":
          type: eval
          description: The expression to obtain the version of MultiQC

authors:
  - "@Loai3tr"
maintainers:
  - "@Loai3tr"
