name: dexseq_count
description: |
  Counts reads overlapping exonic regions for DEXSeq differential exon usage analysis.
keywords:
  - dexseq
  - counting
  - exon usage
  - rna-seq
tools:
  - htseq:
      description: "Analysing high-throughput sequencing data with Python"
      homepage: "https://htseq.readthedocs.io/"
      documentation: "https://htseq.readthedocs.io/en/master/"
      tool_dev_url: "https://github.com/htseq/htseq"
      licence: ["GPL-3.0-only"]
      identifier: "htseq"

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false, lib_type:'ISF' ]`
    - bam:
        type: file
        description: |
          BAM file for exon read counting
        pattern: "*.{bam,bam.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_2572"

  - gff:
      type: file
      description: |
        GFF annotation file prepared by dexseq_prepare_annotation.py
      pattern: "*.gff"
      ontologies:
        - edam: "http://edamontology.org/format_2305"

  - alignment_quality:
      type: integer
      description: |
        Minimum alignment quality score for counting reads
      pattern: "[0-9]+"

output:
  counts:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false, lib_type:'ISF' ]`
      - "*.clean.count.txt":
          type: file
          description: |
            Text file with exon read counts for DEXSeq analysis
          pattern: "*.clean.count.txt"
          ontologies:
            - edam: "http://edamontology.org/format_2330"

  versions_htseq:
    - - "${task.process}":
          type: string
          description: The name of the process
      - htseq:
          type: string
          description: The name of the HTSeq package
      - 'python -c "import pkg_resources; print(pkg_resources.get_distribution(''htseq'').version)"':
          type: eval
          description: The expression to obtain the version of HTSeq

topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - htseq:
          type: string
          description: The name of the HTSeq package
      - 'python -c "import pkg_resources; print(pkg_resources.get_distribution(''htseq'').version)"':
          type: eval
          description: The expression to obtain the version of HTSeq

authors:
  - "@Loai3tr"
maintainers:
  - "@Loai3tr"
