name: "fastq_quant_pseudoalignment"
description: Quantify transcriptome expression using either Kallisto or Salmon pseudo-aligners.
keywords:
  - quantification
  - kallisto
  - salmon
  - pseudoalignment
  - rna-seq
components:
  - kallisto/quant
  - salmon/quant
input:
  - ch_reads:
      type: list
      description: |
        The input channel containing FASTQ files (single or paired-end)
        Structure: [ val(meta), path(reads) ]
      pattern: "*.{fastq,fastq.gz,fq,fq.gz}"
  - ch_kallisto_index:
      type: file
      description: |
        Kallisto transcriptome index file
        Structure: [ val(meta), path(kallisto_index) ]
  - ch_salmon_index:
      type: directory
      description: |
        Salmon transcriptome index directory
        Structure: [ val(meta), path(salmon_index) ]
  - ch_gtf:
      type: file
      description: |
        Genome annotation file (GTF)
        Structure: [ val(meta), path(gtf) ]
  - val_fragment_length:
      type: integer
      description: Estimated average fragment length (required for Kallisto single-end)
  - val_fragment_length_sd:
      type: integer
      description: Estimated standard deviation of fragment length (required for Kallisto single-end)
  - val_pseudoaligner_method:
      type: string
      description: Selected method for quantification ('kallisto' or 'salmon')
output:
  - quant_dir:
      type: directory
      description: |
        Directory containing quantification results (abundance.h5, quant.sf, etc.)
        Structure: [ val(meta), path(quant_dir) ]
  - quant_log:
      type: file
      description: |
        Log files generated during quantification (Kallisto only)
        Structure: [ val(meta), path(log) ]
authors:
  - "@LoaiEletr"
maintainers:
  - "@LoaiEletr"
