name: "picard_markduplicates"
description: Identifies and flags biological (PCR) and technical (optical) duplicate reads to improve variant calling accuracy.
keywords:
  - markduplicates
  - pcr
  - duplicates
  - bam
  - sam
  - deduplication
tools:
  - picard:
      description: |
        A versatile Java-based suite for high-throughput sequencing data manipulation.
        The MarkDuplicates tool specifically handles the identification of identical
        DNA fragments produced during library preparation.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://broadinstitute.github.io/picard/
      licence: ["MIT"]
      identifier: biotools:picard_tools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: Aligned sequence file (BAM) in coordinate-sorted order.
        pattern: "*.bam"
        ontologies:
          - edam: "http://edamontology.org/format_2572"
output:
  - bam:
      - - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
        - "*.bam":
            type: file
            description: Processed BAM file containing updated 0x400 (duplicate) flags in the SAM header.
            pattern: "*.bam"
            ontologies:
              - edam: "http://edamontology.org/format_2572"
  - metrics:
      - - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
        - "*.metrics.txt":
            type: file
            description: Detailed report on duplication rates and estimated library complexity.
            pattern: "*.metrics.txt"
            ontologies: []
  - versions_picard:
      - - ${task.process}:
            type: string
            description: Nextflow process scope that generated the version metadata.
        - picard:
            type: string
            description: The tool name
        - "picard MarkDuplicates --version 2>&1 | sed -n 's/^Version:*//p'":
            type: string
            description: Specific command-line execution used to extract the version number.

topics:
  versions:
    - - ${task.process}:
          type: string
          description: Nextflow process scope that generated the version metadata.
      - picard:
          type: string
          description: The tool name
      - "picard MarkDuplicates --version 2>&1 | sed -n 's/^Version:*//p'":
          type: string
          description: Specific command-line execution used to extract the version number.

authors:
  - "@Loai3tr"
maintainers:
  - "@Loai3tr"
